### ISSUE TITLE
Error mounting route :  mount FullcalendarEngine::Engine => "/fullcalendar_engine" fails

### ISSUE THREAD

**Issue by wayneskillz** [vinsol/fullcalendar-rails-engine#22]
Hi, when i run the command mount FullcalendarEngine::Engine => "/fullcalendar_engine" on my ubuntu terminal i get the error  "bash: /fullcalendar_engine: Permission denied ". i guess this is a problem with my system or so.  i would appreciate if you can explain to me what exactly is happening here. any help will be appreciated.

Also, In the "Declare routes section on your doc", i think it will be better to specify what exactly one is suppose to put in between the quotes " ". i.e. whether to insert full application route or just a subpath to the installation of fullcalender_engine. thanks

**Comment by aditya-kapoor** [comment]
First of all you don't have to run Ubuntu's `mount` command. The `mount` command being referred here is the standard procedure to "mount" Rails Engines in your Rails app. The [Declare Routes] (https://github.com/vinsol/fullcalendar-rails-engine#declare-routes) section requires you to add the specified line in the `routes.rb`.
Before going ahead, I would recommend you to have a reading of the [Rails Engines](http://guides.rubyonrails.org/engines.html) section of Ruby on Rails guides.
That being said, I am giving this issue a close, feel free to open a new one if things still doesn't work out.
